name: ((appli))
director_uuid: 8dd35958-abc4-46fc-9c96-f91c791bfeae

releases:
  - name: mongodb-service
    version: latest

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 1 #<-- important to limit max in flight
  serial: false

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3421.11

instance_groups:
- name: mongodb-server
  release: mongodb-service
#  azs: [z1]
  instances: 3
  vm_type: medium
  env:
    bosh:
      swap_size: 0

  stemcell: trusty
  networks:
  - name: mongo1
  persistent_disk_type: test_disk
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: mongodb-server
    release: mongodb-service
    properties: 
      mongodb-server:
        morDbUserAdminPwd: ((admin_password))
        morDbRootAdminPwd: ((root_password))
        morDbCertificate: 
          ca: ((mongo-certificate.ca))
          private_key: ((mongo-certificate.private_key))
          certificate: ((mongo-certificate.certificate))
        
variables:
- name: admin_password
  type: password
- name: root_password
  type: password
- name: mongo-certificate
  type: certificate
  options:
    is_ca: true
    common_name: mongo-cert
